on: [push, pull_request]

env:
  NODE_VERSION: '12.x' # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm install 
    - name: Build program
      run: npm run build --if-present
    - name: Test program
      run: npm run test --if-present
